// Puerto Rico / Caribbean species (ids 201+). Same shape as EXTRA_FISH.
// Spanish names are the ones anglers in PR actually use, which is what they search for.
const S = (ja, en, es) => (es ? { ja, en, es } : { ja, en });

export const PR_FISH = [
  {
    id: 201, name: "ピーコックバス", nameEn: "Peacock Bass", nameEs: "Tucunaré", emoji: "🐟", category: "caribbean",
    color: "#d8e8b0", accent: "#2f7a2f", difficulty: "beginner", flyFriendly: true,
    season: S("3月〜9月（乾季後半が最盛期）", "March–September (late dry season is the peak)", "Marzo–septiembre (el pico es al final de la seca)"),
    habitat: S("ドス・ボカス湖、カリテ湖などの貯水池。沈み木、岩場、流入河川の合流点、ワンドの浅場。", "Reservoirs such as Dos Bocas and Carite: submerged timber, rocky points, inflow mouths and shallow coves.", "Embalses como Dos Bocas y Carite: palos hundidos, puntas rocosas, la boca de los ríos y ensenadas poco profundas."),
    bestTime: S("日が高い10〜15時。水温が上がるほど活性が上がる珍しい魚。", "Mid-day, 10am–3pm. Unusually, they switch on as the water warms.", "De 10am a 3pm. Al revés que otros peces, se activan cuando el agua se calienta."),
    description: S("南米原産で1960年代にプエルトリコの貯水池に移入された魚。強烈なトップウォーターバイトと引きで、島の淡水釣りの主役。バスと違い日中の高水温を好む。", "Introduced to Puerto Rico's reservoirs from South America in the 1960s. Violent topwater strikes and a bulldog fight make it the island's premier freshwater target. Unlike bass, it wants heat and sun.", "Introducido a los embalses de Puerto Rico desde Suramérica en los años 60. Ataques brutales de superficie y una pelea de toro lo hacen el rey del agua dulce de la isla. A diferencia de la lobina, quiere calor y sol."),
    gear: {
      rod: S("ベイトロッド 6'6\"〜7' MH", "6'6\"–7' medium-heavy baitcaster", "Caña baitcasting 6'6\"–7' medio-pesada"),
      reel: S("ベイトリール（ギア比7:1以上）", "Baitcasting reel, 7:1 or faster", "Carrete baitcasting, 7:1 o más rápido"),
      line: S("PE2〜3号＋フロロリーダー20lb", "30-40lb braid, 20lb fluoro leader", "Trenzada 30-40lb, líder de fluorocarbono 20lb"),
      hooks: S("トレブル#2〜1/0、シングル4/0（ワーム）", "#2–1/0 trebles, 4/0 worm hook", "Anzuelos triples #2–1/0, 4/0 para vinilo"),
      lures: ["Propbait / woodchopper", "Pencil popper", "Jerkbait plateado", "Spinnerbait", "Swimbait color tilapia", "Streamer 6-8wt"],
      tips: S("トップウォーターは速く、うるさく。バイトをミスしても止めずに巻き続けると再アタックしてくる。", "Work topwater fast and loud. If one misses, never stop the retrieve — they come back and hit it again.", "Trabaja la superficie rápido y ruidoso. Si falla el ataque, no pares la recogida: vuelven y atacan otra vez."),
    },
    howTo: [
      { t: S("① ポイントを選ぶ", "1. Pick the water", "1. Escoge el agua"), b: S("ドス・ボカス湖の奥のワンドや流入河川の合流部。沈み木と岩が絡む岸際が一級。ボートかカヤックがあれば有利。", "Back coves and inflow mouths at Dos Bocas. Shorelines mixing timber and rock are prime. A boat or kayak opens up the best water.", "Las ensenadas del fondo y las bocas de los ríos en Dos Bocas. Las orillas con palos y piedra son lo mejor. Con bote o kayak llegas a lo bueno.") },
      { t: S("② タイミング", "2. Timing", "2. El momento"), b: S("晴れた日の日中。水温が26℃を超えてからが本番で、朝夕より昼が強い。", "Sunny days, middle of the day. Once the water passes 26℃ they feed hard — midday beats dawn for this fish.", "Días de sol, al mediodía. Cuando el agua pasa de 26℃ comen fuerte: el mediodía gana sobre el amanecer.") },
      { t: S("③ 誘う", "3. Make the noise", "3. Haz ruido"), b: S("プロップベイトを水面で暴れさせながら高速リトリーブ。静かなアプローチより騒がしいほうが寄る。", "Rip a propbait across the surface at speed. Noise attracts them rather than spooking them.", "Pasa un propbait por la superficie a toda velocidad. El ruido los atrae en vez de espantarlos.") },
      { t: S("④ ファイト", "4. The fight", "4. La pelea"), b: S("フッキングは強く。障害物に突っ込むのでドラグは締め気味、主導権を渡さない。", "Set hard. They bolt for structure, so keep the drag tight and never give them the lead.", "Clava fuerte. Se van para la estructura, así que aprieta el freno y no les des ventaja.") },
    ],
    spots: [{ name: "Lago Dos Bocas", rating: 4.9 }, { name: "Lago Carite", rating: 4.6 }, { name: "Lago La Plata", rating: 4.5 }],
    regulations: S("淡水の貯水池はDRNA（天然資源環境省）の管轄。最新のサイズ・数量制限を確認。", "Freshwater reservoirs are managed by the DRNA — check current size and bag limits.", "Los embalses los maneja el DRNA — verifica los límites de talla y cantidad vigentes."),
  },
  {
    id: 202, name: "クレバルジャック", nameEn: "Jack Crevalle", nameEs: "Jurel", emoji: "🐟", category: "caribbean",
    color: "#f0e2a8", accent: "#b8860b", difficulty: "beginner", flyFriendly: true,
    season: S("通年", "Year-round", "Todo el año"),
    habitat: S("河口、港、桟橋、マングローブの水路、サーフ。ボイルを見つけたら即キャスト。", "Estuaries, harbours, piers, mangrove channels and the surf. Cast at any bust-up you see.", "Estuarios, puertos, muelles, canales de mangle y la orilla. Tira a cualquier reventón que veas."),
    bestTime: S("朝夕のマヅメ。潮が動いている時間帯。", "Dawn and dusk, and any time the tide is running.", "Al amanecer y al atardecer, y siempre que la marea esté corriendo."),
    description: S("プエルトリコ全島で最も身近で最も引く魚。サイズを問わず全力で走り、ライトタックルでは手に負えないことも。食味は良くないためリリースが基本。", "The most available hard fight on the island. Pound for pound nothing pulls like it, and a big one will humble light tackle. Poor eating — almost always released.", "La pelea más disponible de la isla. Libra por libra nada tira como un jurel, y uno grande te humilla el equipo liviano. No es bueno de comer — casi siempre se suelta."),
    gear: {
      rod: S("7'〜8' MH スピニング", "7'–8' medium-heavy spinning", "Caña spinning 7'–8' medio-pesada"),
      reel: S("4000〜6000番スピニング", "4000–6000 spinning", "Carrete spinning 4000–6000"),
      line: S("PE2〜3号＋リーダー40lb", "30-40lb braid, 40lb leader", "Trenzada 30-40lb, líder de 40lb"),
      hooks: S("シングル4/0〜6/0", "4/0–6/0 single hooks", "Anzuelos 4/0–6/0"),
      lures: ["Popper", "Pencil / stickbait", "Metal jig 20-40g", "Bucktail jig", "Clouser minnow 9wt"],
      tips: S("ボイルの先にキャストして群れを追い越させる。フックをシングルに替えると手返しが早くリリースも楽。", "Cast ahead of the school and let them run onto it. Swapping trebles for singles speeds up release.", "Tira adelante del cardumen y deja que lleguen al señuelo. Cambiar los triples por anzuelos sencillos agiliza soltarlos."),
    },
    howTo: [
      { t: S("① 群れを探す", "1. Find the school", "1. Busca el cardumen"), b: S("鳥が騒ぐ場所、水面が沸く場所を目で探す。港内や桟橋の明暗部も定番。", "Watch for working birds and busting bait. Harbour mouths and pier lights are reliable too.", "Busca aves trabajando y sardinas reventando. Las bocas de puerto y las luces de los muelles también son fijas.") },
      { t: S("② 速く引く", "2. Retrieve fast", "2. Recoge rápido"), b: S("ジャックは逃げるものに反応する。止めずに速巻き、ポッパーなら連続で水を弾かせる。", "They chase things that flee. Keep it moving fast; with a popper, keep it spitting water continuously.", "Persiguen lo que huye. Mantenlo rápido; con popper, que no pare de escupir agua.") },
      { t: S("③ ファイトは長期戦", "3. Settle in", "3. Prepárate"), b: S("最初の走りは止まらない。ドラグを出させてから、円を描く動きに合わせてポンピング。", "The first run is unstoppable. Let it take drag, then pump against the circles it swims.", "La primera corrida no se para. Deja que se lleve freno y luego bombea contra los círculos que hace.") },
      { t: S("④ リリース", "4. Release", "4. Suéltalo"), b: S("水から上げすぎず、エラに触れない。大型は食用に向かない（シガテラの懸念）ため速やかに戻す。", "Keep it in the water, off the gills. Big ones are not good eating (ciguatera risk) — send it back quickly.", "Mantenlo en el agua y no le toques las agallas. Los grandes no se comen (riesgo de ciguatera) — devuélvelo rápido.") },
    ],
    spots: [{ name: "Boca de Cangrejos", rating: 4.7 }, { name: "Vieques - Esperanza", rating: 4.5 }, { name: "Fajardo - Las Croabas Flats", rating: 4.5 }],
    regulations: S("大型はシガテラ中毒の報告あり。基本はキャッチ＆リリース。", "Large jacks carry ciguatera risk. Catch and release is the norm.", "Los jureles grandes tienen riesgo de ciguatera. Lo normal es captura y suelta."),
  },
  {
    id: 203, name: "マトンスナッパー", nameEn: "Mutton Snapper", nameEs: "Sama", emoji: "🐠", category: "caribbean",
    color: "#f2c8b0", accent: "#b03a2e", difficulty: "intermediate", flyFriendly: true,
    season: S("通年（4〜6月の産卵期が最盛期）", "Year-round (April–June spawning is the peak)", "Todo el año (el pico es el desove de abril a junio)"),
    habitat: S("サンゴ礁と砂地の境目、水路、浅いフラット周辺の根。", "Reef-to-sand edges, channels and patch reef near the flats.", "El borde entre arrecife y arena, los canales y las cabezas de arrecife cerca de las llanuras."),
    bestTime: S("満月前後の上げ潮。夜明けと日没。", "Around the full moon on a rising tide; first and last light.", "Cerca de la luna llena con marea subiendo; al amanecer y al atardecer."),
    description: S("カリブ屈指の食味を誇る高級魚で、警戒心が非常に強い。砂地に出てエサを探し、危険を察知すると根に戻る。軽い仕掛けで自然に流すのが鉄則。", "One of the best-eating fish in the Caribbean and one of the spookiest. They feed out over sand and retreat to structure at the first sign of trouble, so a light, natural presentation is everything.", "Uno de los mejores pescados de mesa del Caribe y de los más desconfiados. Salen a comer sobre la arena y se meten en la piedra a la primera señal de peligro, así que la presentación liviana y natural lo es todo."),
    gear: {
      rod: S("7' M〜MH スピニング", "7' medium to medium-heavy spinning", "Caña spinning 7' media o medio-pesada"),
      reel: S("4000番スピニング", "4000 spinning", "Carrete spinning 4000"),
      line: S("PE1.5〜2号＋フロロ30lb", "20-30lb braid, 30lb fluorocarbon", "Trenzada 20-30lb, fluorocarbono de 30lb"),
      hooks: S("サークルフック3/0〜5/0", "3/0–5/0 circle hooks", "Anzuelos circulares 3/0–5/0"),
      lures: ["Sardina viva", "Camarón fresco", "Jig + tira de carnada", "Crab fly 9wt"],
      tips: S("リーダーは長め、オモリは軽く。自然に沈むエサにしか口を使わない。", "Long leader, as little weight as you can get away with. They want bait that sinks naturally.", "Líder largo y el menor plomo posible. Quieren carnada que baje natural."),
    },
    howTo: [
      { t: S("① 砂と根の境目を探す", "1. Find the edge", "1. Busca el borde"), b: S("サンゴの塊と白い砂地が接する場所。サマは砂の上でエサを探し、危険を感じると根に戻る。", "Where coral heads meet white sand. Mutton feed out over the sand and bolt back to the rock.", "Donde las cabezas de coral tocan la arena blanca. La sama come sobre la arena y se mete en la piedra si se asusta.") },
      { t: S("② 潮を待つ", "2. Wait for tide", "2. Espera la marea"), b: S("動く潮が絶対条件。止まった潮では食わない。上げ始めの2時間が勝負。", "Moving water is non-negotiable; they will not feed on slack tide. The first two hours of the rise are best.", "El agua tiene que estar corriendo; con marea parada no comen. Las primeras dos horas de subida son las mejores.") },
      { t: S("③ 軽く沈める", "3. Sink it naturally", "3. Déjala bajar natural"), b: S("生きたピルチャードかエビを、できるだけ軽いオモリで潮に乗せて流す。", "Drift a live pilchard or shrimp with the current using the lightest weight that reaches bottom.", "Deriva una sardina viva o un camarón con la corriente, con el plomo más liviano que llegue al fondo.") },
      { t: S("④ 即座に浮かせる", "4. Lift it fast", "4. Súbela rápido"), b: S("食ったら根に入られる前に一気に浮かせる。サークルフックは合わせずに巻き始める。", "Once hooked, get its head up before it reaches structure. With circle hooks, just start reeling — do not strike.", "Al picar, sácale la cabeza antes de que llegue a la piedra. Con anzuelo circular, empieza a recoger: no claves.") },
    ],
    spots: [{ name: "La Parguera", rating: 4.7 }, { name: "Culebra - Luis Peña Channel", rating: 4.5 }, { name: "Vieques - North Shore Reef", rating: 4.5 }],
    regulations: S("最小サイズと数量制限あり。産卵期の規制もあるためDRNAの最新情報を確認。", "Size and bag limits apply, and there are spawning-season rules — check current DRNA regulations.", "Aplican límites de talla y cantidad, y hay reglas por temporada de desove — verifica el reglamento vigente del DRNA."),
  },
  {
    id: 204, name: "イエローテールスナッパー", nameEn: "Yellowtail Snapper", nameEs: "Colirrubia", emoji: "🐠", category: "caribbean",
    color: "#fdf0b8", accent: "#e0a800", difficulty: "beginner", flyFriendly: true,
    season: S("通年", "Year-round", "Todo el año"),
    habitat: S("水深10〜30mのサンゴ礁の上。船の下やチャム（撒き餌）の煙幕に群れで浮く。", "Over reef in 10–30m. They rise off the bottom and hang in a chum slick behind the boat.", "Sobre el arrecife entre 10 y 30m. Suben del fondo y se quedan en la estela de carnada detrás del bote."),
    bestTime: S("日中。チャムを流し続けている間ずっと。", "All day, for as long as you keep the chum going.", "Todo el día, mientras mantengas la carnada molida saliendo."),
    description: S("初めての一匹に最適な、数が釣れて味も良いカリブの定番。チャムで群れを浮かせ、極細リーダーで食わせる釣りが確立している。", "The Caribbean's most reliable bite and excellent on the plate — the best fish to hand a beginner. The game is chumming them up off the reef and fooling them on a very light leader.", "La picada más segura del Caribe y excelente en la mesa — el mejor pez para alguien que empieza. El juego es levantarlos del arrecife con carnada molida y engañarlos con líder bien fino."),
    gear: {
      rod: S("7' L〜M スピニング", "7' light to medium spinning", "Caña spinning 7' liviana o media"),
      reel: S("2500〜3000番スピニング", "2500–3000 spinning", "Carrete spinning 2500–3000"),
      line: S("PE1号＋フロロ15〜20lb（細いほど釣れる）", "10-15lb braid, 15-20lb fluorocarbon — the lighter the better", "Trenzada 10-15lb, fluorocarbono 15-20lb — mientras más fino, mejor"),
      hooks: S("#1〜1/0 の細軸", "#1–1/0 light wire", "Anzuelos #1–1/0 de alambre fino"),
      lures: ["Camarón fresco", "Tiras de bonito", "Jig de 1/4 oz", "Chum bloque", "Shrimp fly 7wt"],
      tips: S("オモリを使わず、チャムと同じ速度でエサを流すのがコツ。見えている魚が食わないときはリーダーをさらに細く。", "Use no weight at all — let the bait drift at exactly the speed of the chum. If they refuse, go lighter on the leader again.", "No uses plomo: deja que la carnada baje a la misma velocidad que el chum. Si no comen, baja más el líder."),
    },
    howTo: [
      { t: S("① チャムを流す", "1. Start the chum", "1. Empieza el chum"), b: S("船を礁の上でアンカリングし、チャムブロックを潮下に流し続ける。15〜20分で群れが浮いてくる。", "Anchor over the reef and keep a chum block working down-current. The school usually rises within 15–20 minutes.", "Fondea sobre el arrecife y mantén el bloque de chum trabajando a favor de corriente. El cardumen sube en 15 o 20 minutos.") },
      { t: S("② 目視で探す", "2. Look for them", "2. Búscalos"), b: S("黄色い尾が船の後ろに見えたら準備完了。魚が見える層にエサを合わせる。", "Once you see yellow tails behind the boat you are in business. Match your bait to the depth they are holding.", "Cuando veas las colas amarillas detrás del bote, ya estás. Pon la carnada a la profundidad donde están.") },
      { t: S("③ ノーシンカーで流す", "3. Drift it free", "3. Deriva sin plomo"), b: S("オモリなしで、ラインを指で送り出しながらチャムと同調させる。抵抗を感じさせない。", "No weight. Feed line off your finger so the bait travels with the chum and feels no resistance.", "Sin plomo. Suelta línea con el dedo para que la carnada viaje con el chum y no sienta resistencia.") },
      { t: S("④ 追い食いさせない", "4. Get it out", "4. Sácalo"), b: S("掛けたら素早く回収。暴れさせると群れが散り、根に潜られてリーダーを切られる。", "Land it quickly — a thrashing fish scatters the school and will cut you off on the reef.", "Sácalo rápido — un pez brincando espanta el cardumen y te corta en el arrecife.") },
    ],
    spots: [{ name: "La Parguera", rating: 4.8 }, { name: "Culebra Island", rating: 4.6 }, { name: "Vieques - North Shore Reef", rating: 4.6 }],
    regulations: S("最小サイズ制限あり。DRNAの規則を確認。", "Minimum size limit applies — check DRNA rules.", "Aplica talla mínima — verifica el reglamento del DRNA."),
  },
  {
    id: 205, name: "レッドハインド（ハタ）", nameEn: "Red Hind (Grouper)", nameEs: "Mero cabrilla", emoji: "🐡", category: "caribbean",
    color: "#f6d2c0", accent: "#8b2500", difficulty: "intermediate", flyFriendly: false,
    season: S("通年（12〜2月は産卵期の禁漁あり）", "Year-round, but a Dec–Feb spawning closure applies", "Todo el año, pero hay veda de desove de diciembre a febrero"),
    habitat: S("水深15〜40mの岩礁帯。穴や棚の中に定位し、あまり動かない。", "Rocky reef in 15–40m. They sit tight in holes and under ledges and do not move far.", "Arrecife rocoso entre 15 y 40m. Se quedan metidos en cuevas y bajo salientes, y no se mueven mucho."),
    bestTime: S("潮が緩む前後。日中でも釣れる。", "Around the tide change; they will bite in full daylight.", "Cerca del cambio de marea; pican hasta de día."),
    description: S("カリブの岩礁を代表するハタで、白身は非常に美味。根に潜られる前に浮かせる勝負が全て。産卵期の保護が重要な魚でもある。", "The classic Caribbean reef grouper and superb eating. The whole fight is the first three seconds — stop it before it reaches its hole. A species where respecting the spawning closure genuinely matters.", "El mero clásico del arrecife caribeño y excelente de comer. Toda la pelea son los primeros tres segundos: párala antes de que llegue a su cueva. Es una especie donde respetar la veda de desove importa de verdad."),
    gear: {
      rod: S("6'6\" H ベイト（ボトム）", "6'6\" heavy conventional or jigging rod", "Caña 6'6\" pesada, convencional o de jigging"),
      reel: S("小型両軸／電動も可", "Conventional reel with strong drag", "Carrete convencional con buen freno"),
      line: S("PE3〜4号＋リーダー60lb", "40-60lb braid, 60lb leader", "Trenzada 40-60lb, líder de 60lb"),
      hooks: S("サークル5/0〜7/0", "5/0–7/0 circle hooks", "Anzuelos circulares 5/0–7/0"),
      lures: ["Calamar", "Sardina entera", "Jig de fondo 100-150g", "Bucktail pesado"],
      tips: S("底を取ったら1〜2m巻き上げて待つ。食ったら即座にリールを巻いて根から引き剥がす。", "Find the bottom, wind up a metre or two and wait. On the bite, crank immediately and pull it away from the rock.", "Toca fondo, sube un metro o dos y espera. Al picar, recoge de inmediato y sácalo de la piedra."),
    },
    howTo: [
      { t: S("① 根を見つける", "1. Mark the rock", "1. Marca la piedra"), b: S("魚探で15〜40mの起伏を探す。平坦な砂地には居ない。", "Use the sounder to find relief in 15–40m. They are never on flat sand.", "Usa la sonda para buscar relieve entre 15 y 40m. Nunca están en arena plana.") },
      { t: S("② 底を切る", "2. Come off the bottom", "2. Sepárate del fondo"), b: S("着底後すぐ1〜2m巻き上げる。底に置いたままだと根掛かりし、魚にも見つけてもらえない。", "Wind up a metre or two the moment you touch down — sitting on the bottom just snags and hides the bait.", "Sube un metro o dos apenas toques fondo — dejarla abajo solo se enreda y esconde la carnada.") },
      { t: S("③ 最初の3秒", "3. The first three seconds", "3. Los primeros tres segundos"), b: S("アタリがあったら迷わず巻く。ポンピングせず、リールの力で根から離す。", "Crank the instant you feel weight. Do not pump — use the reel to drag it clear.", "Recoge en cuanto sientas el peso. No bombees: usa el carrete para sacarlo.") },
      { t: S("④ 禁漁期を守る", "4. Respect the closure", "4. Respeta la veda"), b: S("12〜2月は産卵のため集結し、この時期の捕獲は資源に大きな打撃となる。規制を確認して守る。", "They gather to spawn from December to February, when fishing them does real damage. Check and respect the closure.", "Se agrupan para desovar de diciembre a febrero, y pescarlos entonces hace daño real. Verifica y respeta la veda.") },
    ],
    spots: [{ name: "Vieques - North Shore Reef", rating: 4.6 }, { name: "Culebra - Luis Peña Channel", rating: 4.5 }, { name: "La Parguera", rating: 4.5 }],
    regulations: S("12月〜2月に産卵期の禁漁措置あり。最小サイズ制限も。DRNAの最新規則を必ず確認。", "A December–February spawning closure applies, plus a minimum size. Always check the current DRNA rules.", "Hay veda de desove de diciembre a febrero, además de talla mínima. Verifica siempre el reglamento vigente del DRNA."),
  },
  {
    id: 206, name: "ブルーマーリン（クロカジキ）", nameEn: "Blue Marlin", nameEs: "Aguja azul", emoji: "🗡️", category: "caribbean",
    color: "#bcd8ee", accent: "#12467a", difficulty: "advanced", flyFriendly: false,
    season: S("6月〜10月（8〜9月が最盛期）", "June–October, peaking August–September", "Junio–octubre, con el pico en agosto y septiembre"),
    habitat: S("大陸棚の落ち込み、水深200m以深のブルーウォーター。北岸沖とビエケス南沖が実績。", "The drop-off and blue water beyond 200m. The north coast and the water south of Vieques both produce.", "La caída de la plataforma y el agua azul de más de 200m. La costa norte y el sur de Vieques producen."),
    bestTime: S("朝の出船直後と夕方。潮目とシイラの群れがサイン。", "Early morning and late afternoon. Look for current lines and schools of dorado.", "Temprano en la mañana y al final de la tarde. Busca líneas de corriente y cardúmenes de dorado."),
    description: S("プエルトリコが世界的に有名な理由がこの魚。8〜9月には国際大会も開かれ、300kg級も記録されている。チャーター船での本格的なトローリングが基本。", "The fish Puerto Rico is famous for. International tournaments run in late summer and fish over 600lb have been recorded here. This is a charter-boat trolling game, not a shore one.", "El pez por el que Puerto Rico es famoso. En el verano tardío se corren torneos internacionales y se han registrado ejemplares de más de 600 libras. Esto es curricán desde charter, no pesca de orilla."),
    gear: {
      rod: S("50〜80lbクラスのトローリングロッド", "50–80lb class trolling rod", "Caña de curricán clase 50–80lb"),
      reel: S("両軸トローリングリール 50〜80W", "50–80W lever-drag trolling reel", "Carrete de curricán 50–80W"),
      line: S("モノ80〜130lb", "80-130lb monofilament", "Monofilamento 80-130lb"),
      hooks: S("サークル9/0〜11/0", "9/0–11/0 circle hooks", "Anzuelos circulares 9/0–11/0"),
      lures: ["Skirted trolling lure", "Ballyhoo rigged", "Bala / bonito vivo", "Teasers / dredge"],
      tips: S("サークルフックを使い、アワセずにドラグで掛ける。リリース前提の装備にすると生存率が上がる。", "Fish circle hooks and let the drag set them — never strike. Gear set up for release dramatically improves survival.", "Usa anzuelos circulares y deja que el freno los clave — nunca claves tú. El equipo preparado para soltar mejora muchísimo la supervivencia."),
    },
    howTo: [
      { t: S("① チャーターを取る", "1. Book the boat", "1. Consigue el bote"), b: S("サンフアン、ファハルド、ビエケスから出船。8〜9月は早めの予約が必須。", "Boats run from San Juan, Fajardo and Vieques. August and September book out early.", "Salen botes de San Juan, Fajardo y Vieques. Agosto y septiembre se llenan temprano.") },
      { t: S("② 潮目を流す", "2. Troll the edges", "2. Curriquea los bordes"), b: S("大陸棚の落ち込みや潮目に沿って7〜9ノットでトローリング。ティーザーで船に寄せる。", "Troll 7–9 knots along the drop-off and any current line, working teasers to bring fish to the spread.", "Curriquea a 7–9 nudos por la caída y las líneas de corriente, con teasers para atraerlos al bote.") },
      { t: S("③ 掛ける", "3. The bite", "3. La picada"), b: S("出たら慌てない。サークルフックはアワセ厳禁、ドラグを送りながら魚が反転するのを待つ。", "When one lights up, do nothing fast. With circles, no strike — let the drag come up as the fish turns.", "Cuando aparezca, no hagas nada rápido. Con circulares no claves: deja que el freno suba mientras el pez vira.") },
      { t: S("④ 生かして返す", "4. Release it alive", "4. Suéltala viva"), b: S("長時間のファイトは魚を弱らせる。太めのタックルで短時間で寄せ、船べりでリーダーを切って返す。", "A long fight kills them. Use enough tackle to end it quickly, then cut the leader at the boat.", "Una pelea larga las mata. Usa equipo suficiente para acabar rápido y corta el líder en la borda.") },
    ],
    spots: [{ name: "Vieques - Offshore", rating: 4.9 }, { name: "La Parguera", rating: 4.4 }, { name: "Boca de Cangrejos", rating: 4.5 }],
    regulations: S("国際的にリリースが推奨される魚種。トーナメントでもリリース制が主流。", "International practice is release, and tournaments here are release-format.", "La práctica internacional es soltarla, y los torneos aquí son de captura y suelta."),
  },
  {
    id: 207, name: "キハダマグロ", nameEn: "Yellowfin Tuna", nameEs: "Atún aleta amarilla", emoji: "🐟", category: "caribbean",
    color: "#cfe0f0", accent: "#1f5f8b", difficulty: "advanced", flyFriendly: false,
    season: S("3月〜8月", "March–August", "Marzo–agosto"),
    habitat: S("ブルーウォーター。鳥山、流れ藻、イルカの群れの下につく。", "Blue water, under working birds, weed lines and pods of dolphin.", "Agua azul, bajo aves trabajando, líneas de sargazo y manadas de delfines."),
    bestTime: S("夜明け直後。鳥が動いている間。", "The first hour of light, and any time the birds are working.", "La primera hora de luz, y siempre que las aves estén trabajando."),
    description: S("50〜100lbクラスが春から夏にかけて回遊する。走る距離とスピードは別格で、道具とラインの量が試される。刺身の質も最高。", "Fifty to a hundred pound fish move through from spring into summer. Nothing runs further or faster, and it will test how much line you actually have. Also the best sashimi you will eat.", "Ejemplares de 50 a 100 libras pasan de la primavera al verano. Nada corre más lejos ni más rápido, y pone a prueba cuánta línea tienes de verdad. Además, el mejor sashimi que vas a comer."),
    gear: {
      rod: S("30〜50lbクラス スタンドアップ", "30–50lb class stand-up rod", "Caña stand-up clase 30–50lb"),
      reel: S("両軸 or 大型スピニング（ライン300m以上）", "Conventional or large spinning holding 300m+", "Convencional o spinning grande con 300m o más"),
      line: S("PE4〜6号＋フロロ80lb", "50-65lb braid, 80lb fluorocarbon", "Trenzada 50-65lb, fluorocarbono de 80lb"),
      hooks: S("サークル6/0〜8/0", "6/0–8/0 circle hooks", "Anzuelos circulares 6/0–8/0"),
      lures: ["Cedar plug", "Feather / tuna skirt", "Popper grande", "Sardina viva", "Jig vertical 150-200g"],
      tips: S("鳥山に突っ込まない。群れの手前でエンジンを落とし、キャストで届く距離まで惰性で寄せる。", "Never drive into the birds. Cut the engine short of the school and drift into casting range.", "Nunca entres al medio de las aves. Apaga el motor antes del cardumen y déjate llevar hasta poder tirar."),
    },
    howTo: [
      { t: S("① 鳥を探す", "1. Find the birds", "1. Busca las aves"), b: S("水平線を双眼鏡で探す。海鳥が旋回して降りている場所の下に群れがいる。", "Glass the horizon. Where birds wheel and drop, the tuna are underneath.", "Revisa el horizonte con binoculares. Donde las aves giran y bajan, abajo están los atunes.") },
      { t: S("② 静かに近づく", "2. Approach quietly", "2. Acércate callado"), b: S("群れの100m手前でスローダウン。突っ込むと沈んで二度と浮かない。", "Slow down 100m out. Charging the school puts it down and it will not come back up.", "Baja la velocidad a 100m. Si los atropellas se hunden y no vuelven a subir.") },
      { t: S("③ 掛ける", "3. Hook up", "3. Clávalo"), b: S("キャストか、生き餌を流す。トローリングならシダープラグを群れの縁に通す。", "Cast into them, drift a livebait, or run a cedar plug along the edge of the school if trolling.", "Tírale, deriva carnada viva, o pasa un cedar plug por el borde del cardumen si vas curricaneando.") },
      { t: S("④ 耐える", "4. Hang on", "4. Aguanta"), b: S("最初の走りで200m以上出る。ドラグは触らず、走りが止まってから少しずつ取り返す。", "The first run can take 200m or more. Leave the drag alone and take line back only once it stops.", "La primera corrida puede llevarse 200m o más. No toques el freno y recupera solo cuando pare.") },
    ],
    spots: [{ name: "Vieques - Offshore", rating: 4.8 }, { name: "La Parguera", rating: 4.5 }, { name: "Boca de Cangrejos", rating: 4.4 }],
    regulations: S("大西洋クロマグロ類は国際的な管理下にある。DRNAおよび連邦規則を確認。", "Atlantic tunas are internationally managed — check DRNA and federal rules.", "Los atunes del Atlántico están bajo manejo internacional — verifica las reglas del DRNA y federales."),
  },
  {
    id: 208, name: "セロサワラ", nameEn: "Cero Mackerel", nameEs: "Sierra", emoji: "🐟", category: "caribbean",
    color: "#dfe9f2", accent: "#4a6d8c", difficulty: "beginner", flyFriendly: true,
    season: S("通年（冬〜春が良い）", "Year-round, best in winter and spring", "Todo el año, mejor en invierno y primavera"),
    habitat: S("礁の外縁、防波堤の先端、水路の流れ出し。中層を高速で回遊する。", "Reef edges, the end of breakwaters and channel outflows. They cruise the middle of the water column at speed.", "El borde del arrecife, la punta de los rompeolas y la salida de los canales. Cruzan a media agua y rápido."),
    bestTime: S("朝夕。潮が動いて小魚が流される時間。", "Dawn and dusk, when the tide is pushing baitfish through.", "Amanecer y atardecer, cuando la marea arrastra la carnada."),
    description: S("歯が鋭く、細いラインは一瞬で切られる。銀色のルアーを高速で引くと猛然と食ってくる。身は締まっていて塩焼きにもセビーチェにも良い。", "Razor teeth that will part light line instantly. Burn a silver lure past them and the strike is savage. Firm, clean flesh that grills well and makes good ceviche.", "Dientes de navaja que cortan el líder fino al instante. Pásale un señuelo plateado rápido y el ataque es salvaje. Carne firme que va bien a la parrilla y en ceviche."),
    gear: {
      rod: S("7' M スピニング", "7' medium spinning", "Caña spinning 7' media"),
      reel: S("3000〜4000番", "3000–4000 spinning", "Carrete spinning 3000–4000"),
      line: S("PE1.5〜2号＋ワイヤーリーダー", "20-30lb braid with a short wire trace", "Trenzada 20-30lb con tramo corto de alambre"),
      hooks: S("トレブル#2 or シングル2/0", "#2 trebles or 2/0 singles", "Triples #2 o sencillos 2/0"),
      lures: ["Cuchara plateada", "Metal jig 20-40g", "Tubo plateado curricán", "Clouser plateado 8wt"],
      tips: S("ワイヤーリーダーは短く（15cm程度）。長すぎると見切られ、無いと確実に切られる。", "Keep the wire short — about 15cm. Longer and they see it; without it you will simply get bitten off.", "El alambre bien corto, unos 15cm. Más largo lo ven; sin él te cortan seguro."),
    },
    howTo: [
      { t: S("① 流れの出口に立つ", "1. Stand at the outflow", "1. Párate en la salida"), b: S("防波堤の先端や水路の出口。潮が小魚を押し出す場所にサワラは待っている。", "The tip of a breakwater or the mouth of a channel — anywhere tide flushes bait out, cero are waiting.", "La punta de un rompeolas o la boca de un canal: donde la marea saca la carnada, la sierra espera.") },
      { t: S("② 速く引く", "2. Burn it", "2. Quémalo"), b: S("投げて着水したらすぐ高速リトリーブ。止めるとチェイスをやめる。", "Start cranking the moment it lands and keep it fast — pause and they lose interest.", "Empieza a recoger apenas caiga y mantenlo rápido — si paras, pierden el interés.") },
      { t: S("③ 歯に備える", "3. Respect the teeth", "3. Cuidado con los dientes"), b: S("短いワイヤーを必ず入れる。ランディング時も口元に指を入れない。", "Always run the short wire trace, and never put fingers near the mouth when landing.", "Usa siempre el tramo de alambre corto, y no metas los dedos cerca de la boca al sacarlo.") },
      { t: S("④ すぐ冷やす", "4. Ice it immediately", "4. Ponlo en hielo"), b: S("身が柔らかくなりやすい。締めてすぐ氷に入れると刺身でもいける。", "The flesh softens fast. Bleed it and get it on ice straight away and it is good enough for sashimi.", "La carne se ablanda rápido. Desángralo y ponlo en hielo enseguida y sirve hasta para sashimi.") },
    ],
    spots: [{ name: "Vieques - Mosquito Pier", rating: 4.6 }, { name: "Culebra Island", rating: 4.5 }, { name: "Fajardo - Seven Seas Beach", rating: 4.3 }],
    regulations: S("シガテラの報告は少ないが大型は注意。DRNAの規則を確認。", "Ciguatera reports are rare but take care with large fish. Check DRNA rules.", "Los reportes de ciguatera son raros, pero cuidado con los grandes. Verifica el reglamento del DRNA."),
  },
  {
    id: 209, name: "ソウダガツオ（リトルトゥニー）", nameEn: "Little Tunny (False Albacore)", nameEs: "Bonito", emoji: "🐟", category: "caribbean",
    color: "#cfe6e0", accent: "#25656b", difficulty: "beginner", flyFriendly: true,
    season: S("通年（秋に大群）", "Year-round, with big schools in autumn", "Todo el año, con cardúmenes grandes en otoño"),
    habitat: S("沿岸から沖合の表層。ボイルを作って小魚を追い回す。", "Surface water from just off the beach to well offshore, smashing bait in open water.", "Superficie desde cerca de la orilla hasta mar afuera, reventando carnada en agua abierta."),
    bestTime: S("朝マヅメ。無風で水面が見える日。", "Early morning, especially on calm days when you can see the surface.", "Temprano en la mañana, sobre todo en días calmados cuando se ve la superficie."),
    description: S("食味は一般に落ちるが、引きの強さとフライでの面白さは一級。カジキやサメの餌としても最上で、生き餌に使う人も多い。", "Not prized on the table, but pound for pound one of the best fights available from shore and a fly-rod favourite. Also the finest live bait there is for marlin and shark.", "No es apreciado en la mesa, pero libra por libra es una de las mejores peleas desde la orilla y un favorito de la mosca. Además es la mejor carnada viva que hay para aguja y tiburón."),
    gear: {
      rod: S("7'〜8' M スピニング／9番フライ", "7'–8' medium spinning, or a 9-weight fly rod", "Caña spinning 7'–8' media, o caña de mosca #9"),
      reel: S("3000〜4000番（高速巻取り）", "3000–4000 spinning with a fast retrieve", "Carrete spinning 3000–4000 de recogida rápida"),
      line: S("PE1.5号＋フロロ20lb", "20lb braid, 20lb fluorocarbon", "Trenzada 20lb, fluorocarbono de 20lb"),
      hooks: S("シングル1/0〜3/0", "1/0–3/0 singles", "Anzuelos sencillos 1/0–3/0"),
      lures: ["Metal jig 20-30g", "Epoxy jig", "Small silver spoon", "Surf candy fly 9wt"],
      tips: S("群れの真ん中ではなく、進行方向の前に落とす。小さいルアーほど食う。", "Cast ahead of the school, not into it, and go smaller than feels right — they key on tiny bait.", "Tira adelante del cardumen, no encima, y usa señuelos más pequeños de lo que crees — comen carnada diminuta."),
    },
    howTo: [
      { t: S("① ボイルを見つける", "1. Spot the bust", "1. Ubica el reventón"), b: S("水面が白く沸き、鳥が降りる。岸からでも射程内に入ることが多い。", "Look for white water and diving birds. They often blow up within casting range of the shore.", "Busca agua blanca y aves cayendo. Muchas veces revientan a distancia de tiro desde la orilla.") },
      { t: S("② 前に投げる", "2. Lead the school", "2. Adelántate"), b: S("群れは高速で移動する。今いる場所ではなく、向かう先に落とす。", "The school moves fast — put the lure where it is going, not where it is.", "El cardumen se mueve rápido: pon el señuelo donde va, no donde está.") },
      { t: S("③ 小さく速く", "3. Small and fast", "3. Pequeño y rápido"), b: S("20〜30gの小型メタルを速巻き。サイズを落とすほど反応が良い。", "A small 20–30g metal retrieved fast. Downsizing almost always gets more bites.", "Un metal pequeño de 20-30g recogido rápido. Bajar de tamaño casi siempre da más picadas.") },
      { t: S("④ 使い道を決める", "4. Decide its use", "4. Decide su uso"), b: S("食用にするならすぐ血抜きして氷へ。しない場合は元気なうちに丁寧にリリース、または生き餌に。", "If you are eating it, bleed and ice it at once. If not, release it strong or keep it as livebait.", "Si te lo vas a comer, desangra y hiela de una vez. Si no, suéltalo fuerte o úsalo de carnada viva.") },
    ],
    spots: [{ name: "Vieques - Mosquito Pier", rating: 4.5 }, { name: "Boca de Cangrejos", rating: 4.5 }, { name: "Fajardo - Seven Seas Beach", rating: 4.2 }],
    regulations: S("特別な規制は少ないが、DRNAの一般規則に従う。", "Few specific restrictions, but the general DRNA rules apply.", "Pocas restricciones específicas, pero aplican las reglas generales del DRNA."),
  },
  {
    id: 210, name: "ティラピア", nameEn: "Tilapia", nameEs: "Tilapia", emoji: "🐟", category: "caribbean",
    color: "#e6e8d4", accent: "#6a7a3a", difficulty: "beginner", flyFriendly: true,
    season: S("通年", "Year-round", "Todo el año"),
    habitat: S("貯水池の浅場、岸際、産卵床のある砂泥底。ドス・ボカス湖、カリテ湖に多い。", "Shallow margins of the reservoirs, especially sandy areas holding spawning beds. Common at Dos Bocas and Carite.", "Las orillas poco profundas de los embalses, sobre todo donde hay nidos en fondo arenoso. Abundan en Dos Bocas y Carite."),
    bestTime: S("日中の暖かい時間。産卵期は岸際に集まる。", "Warm parts of the day. During spawning they crowd the shallows.", "Las horas calientes del día. En el desove se juntan en la orilla."),
    description: S("誰でも岸から数釣りできる、島の入門魚。子どもと行く釣りや、食卓のための釣りに最適。産卵床にいる個体は縄張り意識でルアーにも反応する。", "The island's entry-level fish — catchable from the bank by anyone, and the right target to take a kid fishing or to fill a pan. Fish guarding spawning beds will hit a lure out of aggression.", "El pez de entrada de la isla — se pesca desde la orilla sin complicaciones, y es el mejor para llevar a un nene a pescar o para comer. Los que cuidan el nido atacan el señuelo por territorio."),
    gear: {
      rod: S("6'〜7' UL〜L スピニング", "6'–7' ultralight to light spinning", "Caña spinning 6'–7' ultraliviana o liviana"),
      reel: S("1000〜2500番", "1000–2500 spinning", "Carrete spinning 1000–2500"),
      line: S("ナイロン4〜8lb", "4-8lb monofilament", "Monofilamento 4-8lb"),
      hooks: S("#8〜#4 小型", "Small #8–#4", "Anzuelos pequeños #8–#4"),
      lures: ["Pan de masa", "Maíz", "Lombriz", "Micro jig 1/32 oz", "Ninfa pequeña 4wt"],
      tips: S("小さな針と軽いウキ。エサは練り餌かトウモロコシが確実。", "Small hook under a light float. Dough bait or corn is the surest thing.", "Anzuelo pequeño bajo una boya liviana. La masa o el maíz es lo más seguro."),
    },
    howTo: [
      { t: S("① 浅場を探す", "1. Find the shallows", "1. Busca lo bajito"), b: S("岸際で砂泥底が円形に掘られている場所が産卵床。群れでいる。", "Circular depressions scooped in sandy bottom near the bank are spawning beds, and they hold numbers.", "Los hoyos redondos en el fondo arenoso cerca de la orilla son nidos, y ahí hay cantidad.") },
      { t: S("② 軽い仕掛け", "2. Rig light", "2. Monta liviano"), b: S("小針とウキ。オモリは最小限で、エサをゆっくり沈める。", "Small hook, light float, minimum weight so the bait falls slowly.", "Anzuelo pequeño, boya liviana y el mínimo de plomo para que la carnada baje lento.") },
      { t: S("③ 待つ", "3. Wait it out", "3. Espera"), b: S("アタリは小さい。ウキがゆっくり沈んでから合わせる。", "The bite is subtle — let the float go under properly before setting.", "La picada es sutil — deja que la boya se hunda bien antes de clavar.") },
      { t: S("④ 持ち帰る", "4. Take some home", "4. Llévate algunos"), b: S("外来種で資源量も多く、食味も良い。小骨が少なく揚げ物に向く。", "An abundant introduced species and good eating — few small bones, ideal fried whole.", "Especie introducida y abundante, y buena de comer — pocas espinas, ideal frita entera.") },
    ],
    spots: [{ name: "Lago Dos Bocas", rating: 4.5 }, { name: "Lago Carite", rating: 4.6 }, { name: "Lago La Plata", rating: 4.3 }],
    regulations: S("外来種のため持ち帰り制限は緩い。DRNAの規則を確認。", "As an introduced species the take limits are relaxed — check DRNA rules.", "Al ser especie introducida los límites son flexibles — verifica el reglamento del DRNA."),
  },
];
