// Additional species (ids 101+). Same shape as FISH_DATA entries in App.jsx.
// `category` drives the Explore filter (freshwater | saltwater | shore).
const S = (ja, en) => ({ ja, en });

export const EXTRA_FISH = [
  {
    id: 101, name: "アマゴ", nameEn: "Amago Trout", emoji: "🐡", category: "freshwater",
    color: "#3d3b5b", accent: "#e76f51", difficulty: "intermediate", flyFriendly: true,
    flyNote: S("ヤマメと並ぶ渓流フライの代表魚。朱点が美しい。ドライフライへの反応が良い。", "Yamame's red-spotted cousin of western Japan. A classic dry-fly and tenkara target."),
    season: S("3月〜9月（禁漁期あり）", "March–September (closed season applies)"),
    habitat: S("西日本太平洋側の山岳渓流", "Mountain streams of western/Pacific-side Japan"),
    bestTime: S("早朝・夕方・増水後の濁りが取れた頃", "Dawn, dusk, and as rivers clear after rain"),
    description: S("体側の朱点が特徴の渓流魚。ヤマメと近縁で、静岡以西の太平洋側・四国・九州の一部に分布。", "Distinguished by vivid red spots. Closely related to yamame; native from Shizuoka westward on the Pacific side, Shikoku and parts of Kyushu."),
    gear: { rod: S("渓流ロッド 5〜6ft UL / テンカラ竿 3.3〜3.6m / フライ #2〜3", "5–6ft UL rod, 3.3–3.6m tenkara rod, or #2–3 fly rod"), reel: S("1000番スピニング / フライリール", "1000 spinning / fly reel"), line: S("ナイロン 3〜4lb / ティペット 6X〜7X", "3–4lb nylon / 6X–7X tippet"), hooks: S("#12〜16 ドライフライ", "#12–16 dry flies"), lures: ["エルクヘアカディス #14", "パラシュート #14", "スプーン 3g", "逆さ毛鉤"], tips: S("落ち込み下の白泡の脇、流れのヨレを丁寧に流す。足音と影に注意。", "Drift the seams beside the white water below plunges. Move quietly and keep low.") },
    spots: [{ name: "長良川（岐阜）", rating: 4.7, type: S("渓流", "Stream") }, { name: "天川（奈良）", rating: 4.6, type: S("渓流", "Stream") }, { name: "仁淀川（高知）", rating: 4.6, type: S("渓流", "Stream") }],
    regulations: S("遊漁券が必要（各漁協）。禁漁期・体長制限は河川ごとに確認。", "Fishing ticket (遊漁券) required from the local co-op. Check each river's closed season and size limits."),
  },
  {
    id: 102, name: "サクラマス", nameEn: "Cherry Salmon (Sakuramasu)", emoji: "🐟", category: "freshwater",
    color: "#5b2a3d", accent: "#f4a6b8", difficulty: "advanced", flyFriendly: true,
    flyNote: S("スペイ・スイッチロッドでのストリーマー釣りが人気。一生に一匹の価値がある魚。", "Swung streamers on spey or switch rods. Often called a 'fish of a lifetime'."),
    season: S("春（3〜5月の遡上期）", "Spring (March–May run)"),
    habitat: S("大河川の本流・淵", "Main stems and deep pools of large rivers"),
    bestTime: S("朝夕・雪代や増水後の水位が落ち着いた頃", "Dawn and dusk, as snowmelt or high water settles"),
    description: S("ヤマメの降海型。海で大きく育ち、桜の季節に川へ戻る。", "The sea-run form of yamame. Grows large at sea and returns to rivers around cherry-blossom season."),
    gear: { rod: S("ミノーロッド 8〜9ft ML〜M / スペイ #7〜8", "8–9ft ML–M rod / #7–8 spey"), reel: S("2500〜3000番", "2500–3000 spinning / spey reel"), line: S("PE0.8〜1号 + フロロ12〜16lb", "0.8–1 PE + 12–16lb fluoro"), hooks: S("シングルバーブレス推奨", "Single barbless recommended"), lures: ["ヘビーシンキングミノー", "スプーン 14〜18g", "チューブフライ", "インターミディエイトストリーマー"], tips: S("深い淵の流れ込みから開きまで、ルアーを流れに漂わせて見せる。", "Swing lures or flies slowly through pool heads and tailouts.") },
    spots: [{ name: "九頭竜川（福井）", rating: 4.9, type: S("本流", "Main river") }, { name: "神通川（富山）", rating: 4.7, type: S("本流", "Main river") }, { name: "赤川（山形）", rating: 4.6, type: S("本流", "Main river") }],
    regulations: S("河川ごとに専用の遊漁承認証・解禁期間あり。事前に漁協で確認必須。", "Many rivers require a dedicated sakuramasu permit and season — confirm with the co-op before fishing."),
  },
  {
    id: 103, name: "ブラウントラウト", nameEn: "Brown Trout", emoji: "🐠", category: "freshwater",
    color: "#5c4020", accent: "#d9a441", difficulty: "advanced", flyFriendly: true,
    flyNote: S("警戒心が強く、ハッチに合わせた繊細なフライ選択が鍵。夕方のストリーマーも有効。", "Wary and selective — match the hatch. Streamers at dusk for big fish."),
    season: S("春〜秋（地域により通年の管理区間あり）", "Spring–autumn (some managed waters year-round)"),
    habitat: S("湖・湧水河川・本流", "Lakes, spring creeks and larger rivers"),
    bestTime: S("夕マズメ・曇天", "Evening and overcast days"),
    description: S("ヨーロッパ原産。大型化し、魚食性も強い。日本では中禅寺湖や北海道、忍野などで知られる。", "Native to Europe; grows large and turns piscivorous. Known in Japan from Lake Chuzenji, Hokkaido and Oshino."),
    gear: { rod: S("フライ #4〜6 / ミノーロッド 6〜7ft", "#4–6 fly rod / 6–7ft minnow rod"), reel: S("フライリール / 2000番", "Fly reel / 2000 spinning"), line: S("ティペット 5X〜6X / ナイロン 5〜6lb", "5X–6X tippet / 5–6lb nylon"), hooks: S("#12〜18（ハッチに合わせる）", "#12–18, matched to the hatch"), lures: ["CDCダン", "ビーズヘッドニンフ", "ウーリーバガー", "シンキングミノー 5cm"], tips: S("ライズを観察してから一投目を決める。岸際のえぐれを狙う。", "Watch rises before the first cast. Target undercut banks.") },
    spots: [{ name: "中禅寺湖（栃木）", rating: 4.7, type: S("湖", "Lake") }, { name: "忍野・桂川（山梨）", rating: 4.6, type: S("湧水河川", "Spring creek") }, { name: "千歳川（北海道）", rating: 4.5, type: S("河川", "River") }],
    regulations: S("産業管理外来種。放流・移植は禁止。遊漁券・各水域の規則に従う。", "Designated managed invasive species — never release into new waters. Follow local tickets and rules."),
  },
  {
    id: 104, name: "オイカワ", nameEn: "Pale Chub (Oikawa)", emoji: "🐠", category: "freshwater",
    color: "#1d5c7a", accent: "#ff7a59", difficulty: "beginner", flyFriendly: true,
    flyNote: S("里川フライの入門に最適。小さなドライやウェットで数釣りが楽しめる。夏の婚姻色は絶景。", "The perfect intro to fly fishing close to town. Tiny dries and wets; brilliant breeding colors in summer."),
    season: S("4月〜10月（夏が最盛期）", "April–October (peak summer)"),
    habitat: S("平野部の中流域・瀬", "Riffles of lowland mid-rivers"),
    bestTime: S("夕方のライズタイム", "Evening rise"),
    description: S("通称ハヤ・ヤマベ。身近な川で手軽に狙え、テンカラ・フライ入門魚として人気上昇中。", "Also called haya or yamabe. Found in everyday town rivers — a rising favorite for beginner tenkara and fly anglers."),
    gear: { rod: S("フライ #2〜3 / テンカラ竿 3m / 渓流竿", "#2–3 fly rod / 3m tenkara / light pole"), reel: S("フライリール（なくても可）", "Fly reel (optional)"), line: S("ティペット 6X〜7X", "6X–7X tippet"), hooks: S("#16〜20", "#16–20"), lures: ["ソフトハックル #18", "CDCドライ #18", "毛鉤（流し毛鉤）", "サシ（エサ）"], tips: S("浅い瀬の流れに毛鉤を送り込み、小さなアタリに素早く合わせる。", "Swing flies through shallow riffles and strike fast on tiny takes.") },
    spots: [{ name: "筑後川（福岡）", rating: 4.5, type: S("中流", "Mid-river") }, { name: "多摩川（東京）", rating: 4.4, type: S("中流", "Mid-river") }, { name: "鬼怒川（栃木）", rating: 4.4, type: S("中流", "Mid-river") }],
    regulations: S("多くの河川で遊漁券が必要（雑魚券）。", "Most rivers require a basic (雑魚) fishing ticket."),
  },
  {
    id: 105, name: "カワムツ", nameEn: "Dark Chub (Kawamutsu)", emoji: "🐟", category: "freshwater",
    color: "#2f4f3a", accent: "#e8c547", difficulty: "beginner", flyFriendly: true,
    flyNote: S("ドライフライに果敢に飛び出す。子どもや初心者のテンカラに最適。", "Attacks dry flies eagerly — great for kids and first-time tenkara anglers."),
    season: S("4月〜10月", "April–October"),
    habitat: S("西日本の中上流・淵やトロ場", "Pools and slow runs of western Japan's mid-upper rivers"),
    bestTime: S("日中〜夕方", "Midday to evening"),
    description: S("西日本に多い身近な川魚。木陰の淵に群れる。", "A common river fish of western Japan that schools in shaded pools."),
    gear: { rod: S("テンカラ竿 3m / フライ #2〜3", "3m tenkara / #2–3 fly rod"), reel: S("不要〜フライリール", "None or fly reel"), line: S("ティペット 6X", "6X tippet"), hooks: S("#14〜18", "#14–18"), lures: ["テレストリアル（アント）", "エルクヘア #16", "毛鉤"], tips: S("木陰の下や岩陰へ落とす。落下音で寄ってくる。", "Drop flies under overhanging trees — the splash draws them in.") },
    spots: [{ name: "矢部川（福岡）", rating: 4.3, type: S("中流", "Mid-river") }, { name: "菊池川（熊本）", rating: 4.3, type: S("中流", "Mid-river") }, { name: "加古川（兵庫）", rating: 4.2, type: S("中流", "Mid-river") }],
    regulations: S("河川により遊漁券が必要。", "Fishing ticket may be required depending on the river."),
  },
  {
    id: 106, name: "ウグイ", nameEn: "Japanese Dace (Ugui)", emoji: "🐟", category: "freshwater",
    color: "#3b4a5a", accent: "#ff6f61", difficulty: "beginner", flyFriendly: true,
    flyNote: S("ニンフ・ウェットに反応が良い。春の婚姻色（赤い縦帯）が美しい。", "Takes nymphs and wets readily. Striking red stripes in spring spawning colors."),
    season: S("通年（春が最盛期）", "Year-round (peak spring)"),
    habitat: S("上流〜河口まで幅広い", "From headwaters to estuaries"),
    bestTime: S("朝〜昼", "Morning to midday"),
    description: S("日本全国の川に広く分布する丈夫な魚。渓流釣りの外道としてもおなじみ。", "Hardy and found nationwide — a familiar bycatch on trout streams."),
    gear: { rod: S("渓流竿 / フライ #3〜4", "Light pole / #3–4 fly rod"), reel: S("小型スピニング / フライリール", "Small spinning / fly reel"), line: S("ナイロン 3lb / ティペット 5X〜6X", "3lb nylon / 5X–6X tippet"), hooks: S("#12〜16", "#12–16"), lures: ["ビーズヘッドニンフ", "ソフトハックル", "スピナー 2g", "川虫"], tips: S("流れの緩い筋の底付近を流す。", "Drift near the bottom in softer seams.") },
    spots: [{ name: "相模川（神奈川）", rating: 4.2, type: S("中流", "Mid-river") }, { name: "筑後川（福岡）", rating: 4.2, type: S("中流", "Mid-river") }, { name: "千曲川（長野）", rating: 4.3, type: S("中流", "Mid-river") }],
    regulations: S("河川により遊漁券が必要。", "Fishing ticket may be required depending on the river."),
  },
  {
    id: 107, name: "ナマズ", nameEn: "Japanese Catfish (Namazu)", emoji: "🐟", category: "freshwater",
    color: "#3a3326", accent: "#c9b37e", difficulty: "beginner", flyFriendly: false,
    season: S("5月〜9月（梅雨時が最盛期）", "May–September (peak rainy season)"),
    habitat: S("田んぼ周りの水路・平野の川・湖", "Rice-paddy canals, lowland rivers, lakes"),
    bestTime: S("夜・雨後の濁り", "Night and muddy water after rain"),
    description: S("夜行性のトップウォーターゲーム。ポコポコと音を立てるルアーへの派手なバイトが魅力。", "A nocturnal topwater game — explosive strikes on noisy surface lures."),
    gear: { rod: S("ベイトロッド 6〜7ft M〜MH", "6–7ft M–MH baitcasting rod"), reel: S("ベイトリール", "Baitcasting reel"), line: S("PE3〜4号 / ナイロン16〜20lb", "PE 3–4 / 16–20lb nylon"), hooks: S("トレブル・シングル", "Treble or single"), lures: ["ジッターバグ", "羽根モノ", "ポッパー", "フロッグ"], tips: S("バイト直後は合わせず、重みが乗ってから合わせる。", "Don't strike on the splash — wait until you feel weight.") },
    spots: [{ name: "琵琶湖周辺水路（滋賀）", rating: 4.5, type: S("水路", "Canal") }, { name: "筑後川下流域（福岡・佐賀）", rating: 4.4, type: S("河川", "River") }, { name: "利根川（関東）", rating: 4.3, type: S("河川", "River") }],
    regulations: S("私有地の田んぼ・水路への立ち入りに注意。夜間は安全第一で。", "Respect private paddies and canals. Put safety first at night."),
  },
  {
    id: 108, name: "ライギョ", nameEn: "Snakehead (Raigyo)", emoji: "🐍", category: "freshwater",
    color: "#2d3a1f", accent: "#9acd32", difficulty: "advanced", flyFriendly: false,
    season: S("6月〜9月（夏）", "June–September"),
    habitat: S("ハス・ヒシが茂る池沼・クリーク", "Lily-pad and water-chestnut ponds and creeks"),
    bestTime: S("日中の暑い時間帯", "Hot midday hours"),
    description: S("カムルチー・タイワンドジョウなど。水草の上をフロッグで誘う豪快な釣り。", "Northern and blotched snakeheads. Heavy-cover frog fishing with explosive strikes."),
    gear: { rod: S("ライギョ専用ロッド 7ft XH", "7ft XH snakehead rod"), reel: S("ハイギアベイトリール", "High-gear baitcaster"), line: S("PE8〜10号", "PE 8–10"), hooks: S("フロッグのダブルフック", "Frog double hooks"), lures: ["フロッグ", "バズベイト", "スナッグレスポッパー"], tips: S("捕食音やライズを探し、ヒット後は一気に水草から引き剥がす。", "Look for feeding sounds, then winch fish out of the weeds immediately.") },
    spots: [{ name: "手賀沼周辺（千葉）", rating: 4.3, type: S("池沼", "Pond") }, { name: "佐賀平野のクリーク（佐賀）", rating: 4.4, type: S("クリーク", "Creek") }, { name: "巨椋池干拓地周辺（京都）", rating: 4.1, type: S("水路", "Canal") }],
    regulations: S("キャッチ＆リリース推奨。私有地・農業用水路のルールを守る。", "Catch & release encouraged. Respect farm-canal and private-land rules."),
  },
  {
    id: 109, name: "スモールマウスバス", nameEn: "Smallmouth Bass", emoji: "🐟", category: "freshwater",
    color: "#5a4a2a", accent: "#b88a3b", difficulty: "intermediate", flyFriendly: true,
    flyNote: S("ストリーマーやポッパーに好反応。流れのある川でのフライも面白い。", "Great on streamers and poppers — especially fun in flowing rivers."),
    season: S("5月〜11月", "May–November"),
    habitat: S("冷涼な湖・岩盤の多い川", "Cool lakes and rocky rivers"),
    bestTime: S("朝夕・風が当たる岸", "Dawn, dusk, wind-blown banks"),
    description: S("引きの強さはバス随一。東日本の湖や河川で釣れる。", "Pound for pound the hardest-fighting bass. Found in lakes and rivers of eastern Japan."),
    gear: { rod: S("スピニング 6〜7ft L〜ML / フライ #5〜6", "6–7ft L–ML spinning / #5–6 fly"), reel: S("2000〜2500番", "2000–2500 spinning"), line: S("フロロ 4〜6lb", "4–6lb fluoro"), hooks: S("ネコリグ・ダウンショット用", "Finesse hooks"), lures: ["ダウンショット", "ネコリグ", "小型ミノー", "クラウザーミノー"], tips: S("岩や地形変化をボトムで丁寧に探る。", "Work rocks and breaklines slowly along the bottom.") },
    spots: [{ name: "桧原湖（福島）", rating: 4.7, type: S("湖", "Lake") }, { name: "野尻湖（長野）", rating: 4.6, type: S("湖", "Lake") }, { name: "千曲川（長野）", rating: 4.3, type: S("河川", "River") }],
    regulations: S("特定外来生物。生きたままの持ち出し・他水域への放流は法律で禁止。", "Designated invasive species under Japanese law — never transport alive or release elsewhere."),
  },
  {
    id: 110, name: "シロギス", nameEn: "Japanese Whiting (Kisu)", emoji: "🐟", category: "shore",
    color: "#a89f86", accent: "#f2e6c9", difficulty: "beginner", flyFriendly: false,
    season: S("5月〜10月（初夏が最盛期）", "May–October (peak early summer)"),
    habitat: S("砂浜・サーフ・砂底の堤防", "Sandy beaches and sandy-bottom breakwaters"),
    bestTime: S("朝マズメ・日中", "Early morning and daytime"),
    description: S("「砂浜の女王」。投げ釣りの定番で天ぷらが絶品。", "'Queen of the sand beach.' The classic surf-casting target — superb as tempura."),
    gear: { rod: S("投げ竿 3.6〜4m / ちょい投げ ルアーロッド", "3.6–4m surf rod or light lure rod"), reel: S("投げ専用リール / 2500番", "Surf reel / 2500 spinning"), line: S("PE0.8〜1.5号", "PE 0.8–1.5"), hooks: S("キス針 6〜8号", "Kisu hooks #6–8"), lures: ["天秤仕掛け", "石ゴカイ", "キス用ワーム"], tips: S("ゆっくりサビいて、ブルブルというアタリを感じる。", "Drag slowly and feel for the trembling bite.") },
    spots: [{ name: "糸島のサーフ（福岡）", rating: 4.5, type: S("サーフ", "Surf") }, { name: "九十九里浜（千葉）", rating: 4.4, type: S("サーフ", "Surf") }, { name: "吹上浜（鹿児島）", rating: 4.5, type: S("サーフ", "Surf") }],
    regulations: S("海での釣りは基本的に遊漁券不要。漁港は立入禁止区域に注意。", "No license for sea fishing in general — observe no-entry areas in fishing ports."),
  },
  {
    id: 111, name: "カサゴ", nameEn: "Scorpionfish (Kasago)", emoji: "🐟", category: "shore",
    color: "#7a2f1d", accent: "#f08a5d", difficulty: "beginner", flyFriendly: false,
    season: S("通年（冬が美味）", "Year-round (best eating in winter)"),
    habitat: S("堤防のテトラ・岩礁・穴", "Breakwater tetrapods, rocky reefs, crevices"),
    bestTime: S("夕方〜夜", "Evening to night"),
    description: S("穴釣りの定番。根魚の代表で子どもでも簡単に釣れる。", "The classic hole-fishing target — easy for kids and beginners."),
    gear: { rod: S("穴釣り竿 1.2m / ロックフィッシュロッド 7ft", "1.2m hole rod / 7ft rockfish rod"), reel: S("小型ベイト・スピニング", "Small baitcaster or spinning"), line: S("フロロ 8〜12lb", "8–12lb fluoro"), hooks: S("ブラクリ 3〜5号", "Bura-kuri rig #3–5"), lures: ["ブラクリ + サバ切り身", "ジグヘッド + ワーム", "テキサスリグ"], tips: S("テトラの隙間に落として底を取ったらすぐ誘う。根掛かり注意。", "Drop into gaps, touch bottom, then lift immediately to avoid snags.") },
    spots: [{ name: "博多湾の堤防（福岡）", rating: 4.3, type: S("堤防", "Breakwater") }, { name: "城ヶ島（神奈川）", rating: 4.4, type: S("磯", "Rocky shore") }, { name: "伊豆半島の漁港（静岡）", rating: 4.4, type: S("漁港", "Harbor") }],
    regulations: S("テトラ上はライフジャケット必須。背びれの毒棘に注意。", "Wear a life jacket on tetrapods. Beware of venomous dorsal spines."),
  },
  {
    id: 112, name: "タチウオ", nameEn: "Largehead Hairtail (Tachiuo)", emoji: "🐟", category: "shore",
    color: "#6d7a8a", accent: "#e0e6ee", difficulty: "intermediate", flyFriendly: false,
    season: S("8月〜12月（秋が最盛期）", "August–December (peak autumn)"),
    habitat: S("湾内の堤防・常夜灯周り", "Harbor walls and lit piers inside bays"),
    bestTime: S("夕マズメ〜夜", "Dusk into night"),
    description: S("銀色に輝く刀のような魚。秋の夜釣りの人気者。", "A gleaming, sword-shaped fish — the star of autumn night fishing."),
    gear: { rod: S("エギング・シーバスロッド 8〜9ft", "8–9ft eging/seabass rod"), reel: S("2500〜3000番", "2500–3000 spinning"), line: S("PE0.8〜1号 + ワイヤー or フロロ20lb", "PE 0.8–1 + wire or 20lb fluoro"), hooks: S("タチウオテンヤ・ワインド用", "Tachiuo tenya or wind-rig hooks"), lures: ["ワインド", "メタルジグ 20〜30g", "テンヤ + キビナゴ", "電気ウキ仕掛け"], tips: S("日没直後の時合いを逃さない。鋭い歯に注意。", "Don't miss the bite window right after sunset. Mind the razor teeth.") },
    spots: [{ name: "大阪湾（大阪・兵庫）", rating: 4.6, type: S("堤防", "Breakwater") }, { name: "東京湾（船）", rating: 4.5, type: S("船", "Boat") }, { name: "関門海峡周辺（福岡・山口）", rating: 4.3, type: S("堤防", "Breakwater") }],
    regulations: S("夜間の堤防は足元注意。立入禁止区域に入らない。", "Watch your footing at night and stay out of restricted areas."),
  },
  {
    id: 113, name: "マゴチ", nameEn: "Bartail Flathead (Magochi)", emoji: "🐊", category: "shore",
    color: "#6b5b3e", accent: "#c8a96e", difficulty: "intermediate", flyFriendly: false,
    season: S("5月〜9月", "May–September"),
    habitat: S("サーフ・河口の砂泥底", "Sandy/muddy bottoms of surf and estuaries"),
    bestTime: S("朝夕マズメ", "Dawn and dusk"),
    description: S("「照りゴチ」と呼ばれる夏の高級魚。ヒラメと並ぶサーフの人気ターゲット。", "A prized summer fish — alongside flounder, the top surf-lure target."),
    gear: { rod: S("サーフロッド 9.6〜10ft", "9.6–10ft surf rod"), reel: S("3000〜4000番", "3000–4000 spinning"), line: S("PE1〜1.2号 + フロロ20lb", "PE 1–1.2 + 20lb fluoro"), hooks: S("ジグヘッド 21〜28g", "21–28g jig heads"), lures: ["ジグヘッド + ワーム", "メタルジグ", "シンキングペンシル"], tips: S("ボトムを跳ねさせず、ズル引きで砂煙を立てる。", "Drag along the bottom to kick up sand rather than hopping.") },
    spots: [{ name: "有明海沿岸（福岡・佐賀）", rating: 4.2, type: S("干潟・河口", "Tidal flat") }, { name: "相模湾サーフ（神奈川）", rating: 4.4, type: S("サーフ", "Surf") }, { name: "遠州灘（静岡）", rating: 4.5, type: S("サーフ", "Surf") }],
    regulations: S("エラ蓋の棘に注意。フィッシュグリップ推奨。", "Beware of gill-cover spines — use a fish grip."),
  },
  {
    id: 114, name: "ハゼ", nameEn: "Yellowfin Goby (Haze)", emoji: "🐟", category: "shore",
    color: "#8a7a5a", accent: "#e8d8a8", difficulty: "beginner", flyFriendly: false,
    season: S("7月〜11月（秋が最盛期）", "July–November (peak autumn)"),
    habitat: S("河口・運河・干潟", "Estuaries, canals and tidal flats"),
    bestTime: S("上げ潮時の日中", "Daytime on a rising tide"),
    description: S("マハゼ。ファミリーフィッシングの定番で、天ぷらが絶品。", "The go-to family fishing target in autumn — delicious as tempura."),
    gear: { rod: S("ちょい投げロッド / のべ竿 3〜4m", "Light casting rod / 3–4m pole"), reel: S("1000〜2000番", "1000–2000 spinning"), line: S("ナイロン 3〜4lb", "3–4lb nylon"), hooks: S("ハゼ針 5〜7号", "Goby hooks #5–7"), lures: ["ミャク釣り仕掛け", "青イソメ", "ハゼクランク"], tips: S("底をゆっくり引いて、コツコツの前アタリで待ってから合わせる。", "Drag slowly on the bottom; wait through the first taps before setting.") },
    spots: [{ name: "旧江戸川（東京・千葉）", rating: 4.4, type: S("河口", "Estuary") }, { name: "室見川河口（福岡）", rating: 4.3, type: S("河口", "Estuary") }, { name: "松島湾（宮城）", rating: 4.3, type: S("湾", "Bay") }],
    regulations: S("河口域は漁業権が設定されている場合あり。現地の表示を確認。", "Some estuaries have fishing rights — check local signage."),
  },
];

export const EXTRA_FISH_EMOJI = Object.fromEntries(EXTRA_FISH.map(f => [f.id, f.emoji]));
